import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import nicho from "../public/nicho.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nicholas Bridgemohan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900  font-robertomono">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:fill-white">
            <h1 className="text-xl dark:text-white">developedbynic</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:fill-white"
                />
              </li>
              <li>
                <a
                  className="
                  text-white px-4 py-2 rounded-md ml-8 bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2
              className="
            text-4xl py-2 font-medium md:text-6xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Nicholas Bridgemohan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              Senior Developer Extraordinaire
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-xl mx-auto  text-gray-800 dark:text-gray-300">
              I am a highly skilled and experienced developer with a strong
              background in back-end technologies using Javascript, PHP and Java
              and constantly in pursuit of learning more.
            </p>
          </div>

          <div
            className="
          relative mx-auto rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96
          bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
          >
            <Image
              alt="plz hire me :("
              src={nicho}
              fill
              style={{ objectFit: "cover" }}
            />
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 mt-12 text-gray-600">
            <a target="_blank" href="https://twitter.com/sqrpants">
              <AiFillTwitterCircle className="dark:fill-white" />
            </a>
            <a target="_blank" href="https://www.linkedin.com/in/bridgemohan/">
              <AiFillLinkedin className="dark:fill-white" />
            </a>
            <a target="_blank" href="https://www.youtube.com/@bridgemohan">
              <AiFillYoutube className="dark:fill-white" />
            </a>
          </div>
        </section>
        {/* 
        <section>
          <div className="text-center">
            <h3 className="text-2xl py-2">Services I offer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              text text text text text text text text text text text text text
              text text text text text text text text text text text text text
              text text text text text text
              <span className="text-teal-400">span text wowwwo</span> text text
              text text text text text text text text text text text asfgasd
            </p>
          </div>

          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={consulting}
                alt="consulting"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p>Creating elegant designs suiteed for your design theory</p>
              <h4>Tools I used</h4>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                alt="design"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p>Creating elegant designs suiteed for your design theory</p>
              <h4>Tools I used</h4>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={code}
                alt="code"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p>Creating elegant designs suiteed for your design theory</p>
              <h4>Tools I used</h4>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
              <p className="text-gray-800 py-1">test1</p>
            </div>
          </div>
        </section> */}

        <section>
          <div className="text-center p-10 py-10">
            <h2
              className="
            text-3xl py-2 font-medium md:text-5xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Experience
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              Senior Developer Extraordinaire
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-xl mx-auto  text-gray-800 dark:text-gray-300">
              I am a highly skilled and experienced developer with a strong
              background in back-end technologies using Javascript, PHP and Java
              and constantly in pursuit of learning more.
            </p>
          </div>

          <div className="">
            <h3 className="text-2xl text-gray-700 font-bold mb-6 ml-3">
              Latest News
            </h3>

            <ol>
              <li className="border-l-2 border-purple-600">
                <div className="md:flex flex-start self-center">
                  <div className="bg-purple-600 w-6 h-6 flex items-center justify-center rounded-full -ml-3.5"></div>
                  <div className="block p-6 rounded-lg shadow-lg bg-gray-100 max-w-md ml-6 mb-10">
                    <div className="flex justify-between mb-4">
                      <a
                        href="#!"
                        className="font-medium text-purple-600 hover:text-purple-700 focus:text-purple-800 duration-300 transition ease-in-out text-sm"
                      >
                        New Web Design
                      </a>
                      <a
                        href="#!"
                        className="font-medium text-purple-600 hover:text-purple-700 focus:text-purple-800 duration-300 transition ease-in-out text-sm"
                      >
                        04 / 02 / 2022
                      </a>
                    </div>
                    <p className="text-gray-700 mb-6">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Quisque scelerisque diam non nisi semper, et elementum
                      lorem ornare. Maecenas placerat facilisis mollis. Duis
                      sagittis ligula in sodales vehicula.
                    </p>
                    <button
                      type="button"
                      className="inline-block px-4 py-1.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out"
                      data-mdb-ripple="true"
                    >
                      Preview
                    </button>
                    <button
                      type="button"
                      className="inline-block px-3.5 py-1 border-2 border-purple-600 text-purple-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                      data-mdb-ripple="true"
                    >
                      See demo
                    </button>
                  </div>
                </div>
              </li>
            </ol>
          </div>
          {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web1"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web2"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web3"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web4"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web5"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web6"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div> */}
        </section>

        <footer>
          <div className="text-center">
            <p>&#169; 2023 Nicholas Bridgemohan</p>
          </div>
        </footer>
      </main>
    </div>
  );
}
